language: java

jdk:
  - oraclejdk9

os:
  - linux

git:
  depth: 1

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2

install: ./clone-repos.sh

script:
  - mvn install -DskipTests=true
  - mvn javadoc:aggregate-jar -DskipTests=true
  - ./gradlew -Dorg.ajoberstar.grgit.auth.username=${username} -Dorg.ajoberstar.grgit.auth.password=${password} gitPublishPush
