language: java

jdk:
  - oraclejdk9

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2
  
git:
  depth: false

install: ./clone-repos.sh

script:
  - mvn javadoc:aggregate-jar
  - ./gradlew -Dorg.ajoberstar.grgit.auth.username=${username} -Dorg.ajoberstar.grgit.auth.password=${password} gitPublishPush
